---
title: "Schedule and Course Materials"
subtitle: "Winter School - Iesp UERJ"
---

Here you can find all materials (readings, slides, code, datasets, assignments) for the class.

## Day 1 - Introduction & Neural Networks

-   [Slides](slides/day_1.html)

-   **Code**:

    -   Logistic Regression as Neural Networks: <a href="/code/day_1_logistic_nn.ipynb" download> notebook </a>

    -   [Introduction to Pytorch](https://docs.pytorch.org/tutorials/beginner/introyt/introyt1_tutorial.html)

-   **Readings**:

    -   [SLP: Chapters 7](https://stanford.edu/~jurafsky/slp3/7.pdf)

    -   [Lin, Gechun, and Christopher Lucas. "An Introduction to Neural Networks for the Social Sciences." (2023)](https://christopherlucas.org/files/PDFs/nn_chapter.pdf)

    -   One hour youtube video from MIT Intro to Deep Learning: https://www.youtube.com/watch?v=alfdI7S6wCY&list=PLtBw6njQRU-rwp5\_\_7C0oIVt26ZgjG9NI&index=1

## Day 2 - Word Embeddings

-   [Slides](slides/day_1.html)

-   **Code**:

-   **Readings**:

-   **Theory Papers**:

    -   [SLP Chapter 6, Vector Semantics and Embeddings](https://stanford.edu/~jurafsky/slp3/6.pdf)

    -   [Meyer, David. How Exactly Does Word2Vec Work?](https://swimm.io/learn/large-language-models/what-is-word2vec-and-how-does-it-work)

    -   [Spirling and Rodriguez, Word embeddings: What works, what doesn't, and how to tell the difference for applied research](https://github.com/ArthurSpirling/EmbeddingsPaper)

-   **Applied Papers**:

    -   [Austin C. Kozlowski, Austin C., Matt Taddy, and James A. Evans. 2019. "The Geometry of Culture: Analyzing the Meanings of Class through Word Embeddings." American Sociological Review 84, no. 5: 905--49. https://doi.org/10.1177/0003122419877135]()

    -   [Garg, Nikhil, Londa Schiebinger, Dan Jurafsky and James Zou. 2018. "Word embeddings quantify 100 years of gender and ethnic stereotypes." Proceedings of the National Academy of Sciences 115(16):E3635--E3644.](https://www.pnas.org/doi/10.1073/pnas.1720347115)

    -   [Rodman, E., 2020. A Timely Intervention: Tracking the Changing Meanings of Political Concepts with Word Vectors. Political Analysis, 28(1), pp.87-111]()

    -   [Rheault, Ludovic, and Christopher Cochrane. "Word embeddings for the analysis of ideological placement in parliamentary corpora." Political Analysis 28, no. 1 (2020): 112-133.](https://www.cambridge.org/core/journals/political-analysis/article/word-embeddings-for-the-analysis-of-ideological-placement-in-parliamentary-corpora/017F0CEA9B3DB6E1B94AC36A509A8A7B)

    -   [Gennaro, Gloria, and Elliott Ash. "Emotion and reason in political language." The Economic Journal 132, no. 643 (2022): 1037-1059.](https://academic.oup.com/ej/article/132/643/1037/6490125)

## Day 3 - Transformers

## Day 4 - Large Language Models
