---
title: "Advanced Text-As-Data - Winter School - Iesp UERJ"
subtitle: "<span style = 'font-size: 140%;'> <br> Days 3 and 4: Transformers, Pre-Trained Models, and LLMs"
author: "<span style = 'font-size: 120%;'> Professor: Sebastián Vallejo </span>"
execute: 
  echo: false
  error: true
  cache: true
format:
  revealjs: 
    transition: slide
    background-transition: fade
    code-line-numbers: false
    width: 1200
    height: 800
    center: false
    slide-number: true
    incremental: false
    chalkboard: 
      buttons: false
    preview-links: auto
    footer: "Text-as-Data"
    theme: [simple, custom.scss]
editor_options: 
  chunk_output_type: console
---

# Transformers, Pre-Trained Models, and LLMs

## What to Expect?

In the last two days you learned some heavy matrix algebra, dot-product, sigmoid-function, mostly-black-magic-believe-in-me content. Now we will enter the paradox of complexity: the material we will learn today is so complex that it is best understood through intuition and experience. 

The material will be divided into three parts:

  - Transformers: lecture-heavy introduction to the Transformers architecture. 
  - Pre-trained models: applying the Transformers architecture to pre-trained models and implementing it (code).
  - Large Language Models (LLMs): learn about Large Language models (LLMs), their applications and limitations, and how to implement LLMs (code).

## Material

Here is where you can find all the lectures and code we will be using during the next two days:

1. Slides for "Introduction to Transformers": [link.](https://github.com/svallejovera/iesp-uerj/blob/main/IESP_Transformers.pdf)
2. Slides for "Pre-Trained Transformers-Based Models": [link.](https://github.com/svallejovera/iesp-uerj/blob/main/IESP_Pre_Trained_Models.pdf)
3. Code for:
    i) Using Fine-Tuned Models: [link.](https://colab.research.google.com/drive/1IrKX1W0h4HTw3SmcvrMlv9CBWAUS44fw#scrollTo=VtypFSfiWfcS)
    ii) Fine-Tuning a Model: [link.](https://colab.research.google.com/drive/1t18hP-yngLEEvSgiMSUD1FrDpzTWdTfG#scrollTo=vuKuXDDyxF2M)
    iii) Further Pre-Training a Model: [link.](https://colab.research.google.com/drive/1_nmDGG_OzU3MjIa4T6JZTD_ra6kAa0wW#scrollTo=5p8Ok39iGEEU) 

---

4. Slides for "A Primer on Large Language Models": [link.](https://github.com/svallejovera/iesp-uerj/blob/main/IESP_LLMs.pdf) 
5. Code for:
    i) Using LLMs: [link.](https://colab.research.google.com/drive/10D2nZ0NolNk_KZBYQaC9tqwmNG9JIDTE#scrollTo=dYsBItY2QB84) 
    ii) LLMs as Annotators: [link.](https://colab.research.google.com/drive/19KXG7mauoCBwNfyvwR6mrXsAXS4TgX86#scrollTo=lpEniq0rSeZV) 
  
